version: '3.8'

services:
  file-management-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-management-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      # 앞 부분은 Container 에서 활용할 ENV 이름
      # 뒷 부분은 현재 docker compose 실행할 때, 실행 환경에서 읽어올 ENV 이름
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_S3_BASE_URL=${AWS_S3_BASE_URL}
